### ISSUE TITLE
 Push notifications on Android 8 causes app crashes

### ISSUE THREAD

**Issue by fxc-dev** [Donky-Network/cordova-plugin-donky-jsmodular#8]
When user with Android 8+ receives push notification it causes application crash:

`Fatal Exception: java.lang.RuntimeException: Unable to start receiver net.donky.core.gcm.DonkyGcmBroadcastReceiver: java.lang.IllegalStateException: Not allowed to start service Intent { act=com.google.android.c2dm.intent.RECEIVE flg=0x1000030 pkg=org.fxclub.libertex cmp=org.fxclub.libertex/net.donky.core.gcm.DonkyGcmIntentService (has extras) }: app is in background uid UidRecord{7d1bb14 u0a213 RCVR bg:+7h19m43s806ms idle procs:1 seq(0,0,0)}
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:3397)
       at android.app.ActivityThread.-wrap18(Unknown Source)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1780)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6938)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)`

`Caused by java.lang.IllegalStateException: Not allowed to start service Intent { act=com.google.android.c2dm.intent.RECEIVE flg=0x1000030 pkg=org.fxclub.libertex cmp=org.fxclub.libertex/net.donky.core.gcm.DonkyGcmIntentService (has extras) }: app is in background uid UidRecord{7d1bb14 u0a213 RCVR bg:+7h19m43s806ms idle procs:1 seq(0,0,0)}
       at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1538)
       at android.app.ContextImpl.startService(ContextImpl.java:1484)
       at android.content.ContextWrapper.startService(ContextWrapper.java:663)
       at android.content.ContextWrapper.startService(ContextWrapper.java:663)
       at android.support.v4.content.WakefulBroadcastReceiver.startWakefulService(WakefulBroadcastReceiver.java:99)
       at net.donky.core.gcm.DonkyGcmBroadcastReceiver.onReceive(DonkyGcmBroadcastReceiver.java:32)
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:3390)
       at android.app.ActivityThread.-wrap18(Unknown Source)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1780)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6938)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)`

**Comment by Univibe69** [comment]
Hi  @fxc-dev , I think you have posted your issue in the wrong repo.

I believe this is where you want to log that:

https://github.com/Donky-Network/DonkySDK-Android-Modular

Kind regards

**Comment by fxc-dev** [comment]
No, it's not correct at all, we use only one cordova-plugin-donky-jsmodular in our cordova application both for Android and iOS, not the separate DonkySDK-Android-Modular

**Comment by Univibe69** [comment]
Hi, I hope you have resolved your issue. These are the only native files from us that you should have in '/platforms/android/src' 

![screenshot 2018-11-07 at 11 14 39](https://user-images.githubusercontent.com/1167369/48128426-5a16cb00-e27e-11e8-8ee7-70ae75c49b0f.png)

**Comment by fxc-dev** [comment]
https://github.com/fxc-dev/cordova-plugin-donky-jsmodular/commit/7967dc84ff9d47039447cccaadcd4a68e384641e

This changes with setting compile sdk version to 26 - fixed the problem
